desc "Update Fidgetech CR links to point to new curriculum org"
task :tmp_update_fidgetech_cr_links => [:environment] do
  fromArray = ['https://github.com/epicodus-classroom/fidgetech-csharp-dotnet-5/blob/main/1_test_driven_development_with_c/5a_cr_teacher_c_sharp_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-csharp-dotnet-5/blob/main/2_basic_web_apps/5a_teacher_notes_basic_mvc_web_apps.md', 'https://github.com/epicodus-classroom/fidgetech-csharp-dotnet-5/blob/main/3_database_basics/5b_teachers_notes_database_basics_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-csharp-dotnet-5/blob/main/4_many_to_many_relationships/5a_teachers_notes_advanced_databases_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-csharp-dotnet-5/blob/main/5_authentication_with_identity/5a_teachers_notes_authentication_with_identity_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-csharp-dotnet-5/blob/main/6_apis/5a_cr_building_an_api_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-intro/blob/main/2_javascript_and_web_browsers/5a_cr_javascript_and_web_browsers_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-intro/blob/main/3_arrays_and_looping/5a_cr_arrays_and_looping_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-javascript/blob/main/1_new_object_oriented_javascript/5a_cr_object_oriented_javascript_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-javascript/blob/main/2_new_test_driven_development/5a_teacher_tdd_with_javascript_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-javascript/blob/main/3_new_asynchrony_and_apis/5a_teacher_asynchrony_and_apis_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-react-new/blob/main/0_functional_programming/5a_cr_functional_programming_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-react-new/blob/main/1_react_fundamentals/5a_cr_react_fundamentals_ONE_week_independent_project.md', 'https://github.com/epicodus-classroom/fidgetech-react-new/blob/main/2_redux/5a_epicenter_cr_redux_independent_project_capstone_work_.md', 'https://github.com/epicodus-classroom/fidgetech-shared-curriculum/blob/main/team_week/team_week_cr.md']
  toArray = ['https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/c_sharp_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/basic_mvc_web_apps.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/database_basics_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/advanced_databases_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/authentication_with_identity_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/building_an_api_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/javascript_and_web_browsers_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/arrays_and_looping_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/object_oriented_javascript_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/tdd_with_javascript_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/asynchrony_and_apis_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/functional_programming_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/react_fundamentals_ONE_week_independent_project.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/redux_independent_project_capstone_work_.md', 'https://github.com/epicodus-curriculum/code-reviews/blob/main/fidgetech/team_week_cr.md']
  mapping = {}
  fromArray.each_with_index do |from, index|
    mapping[from] = toArray[index]
  end

  mapping.each do |from, to|
    puts "From: #{from.gsub('https://github.com/', '')}"
    puts "To: #{to.gsub('https://github.com/', '')}"
    puts ''
    CodeReview.where(github_path: from).update_all(github_path: to)
  end
end
