ruby '3.2.2'

source 'https://rubygems.org'

gem 'rails', '~> 7.0.4.2'
gem 'pg'
gem 'uglifier'
gem 'jquery-rails'
gem 'coffee-script'
gem 'devise'
gem 'devise_invitable'
gem 'stripe'
gem 'mailgun-ruby'
gem 'nested_form_fields'
gem 'redcarpet'
gem 'deep_cloneable'
gem 'cancancan'
gem 'jquery-ui-rails'
gem 'validate_url'
gem 'hellosign-api'
gem 'closeio'
gem 'bootstrap-datepicker-rails'
gem 'jquery-timepicker-rails'
gem 'bootswatch-rails'
gem 'bootstrap-sass'
gem 'sass-rails'
gem 'jquery-datatables-rails'
gem 'textacular'
gem 'omniauth-github'
gem 'omniauth-rails_csrf_protection'
gem 'font-awesome-rails'
gem 'bootstrap-multiselect-rails'
gem 'kaminari'
gem 'paranoia'
gem 'resque'
gem 'active_model_serializers'
gem 'rest-client'
gem 'plaid'
gem 'openssl'
gem 'jwt'
gem 'octokit'
gem 'httparty'
gem 'sprockets-rails'
gem 'devise-two-factor'
gem 'rqrcode-rails3'

group :development do
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem "letter_opener"
  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'listen'
  gem 'timecop'
  gem 'wicked_pdf'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'pry'
  gem 'hirb'
  gem 'factory_bot_rails', '~> 4.11'
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '4.0.0.rc1'
  gem 'launchy'
  gem 'poltergeist'
  gem 'database_cleaner'
  gem 'webmock'
  gem 'vcr'
  gem 'simplecov'
  gem 'simplecov-lcov', '~> 0.8.0'
  gem 'coveralls_reborn', '~> 0.26.0', require: false
  gem 'stripe-ruby-mock', '~> 3.1.0.rc3', :require => 'stripe_mock'
  gem 'faker'
end

group :production do
  gem 'rails_12factor'
  gem 'puma', '< 6'
  gem 'newrelic_rpm'
  gem 'bugsnag'
  gem 'lograge'
  gem 'oink'
end
